//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public int movieID { get; set; }
        public string title { get; set; }
        public string language { get; set; }
        public int length { get; set; }
        public string imdb { get; set; }
        public string director { get; set; }
        public string genre { get; set; }
    }
}
